service: racecar
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs20.x
  stage: prod
  profile: personal
  region: ap-southeast-1

functions:
  api:
    handler: index.handler
    events:
      - httpApi: '*'
